const text = [
"Person With Machete",
"Permission to Pit Granted",
"Request Permission to Pit",
"Git n Go Robbery",
"Intox Driver",
"Car Chase",
"Foot Chase",
"Suspect on a Bicycle",
"10-99 Wanted Person",
"Hazmat Response",
"Shooting Victim",
"'Shots Heard' Were Fireworks",
"No Plates",
"Court Ave Fight",
"Drive-By Shooting",
"Stabbing Victim",
"Victim Dropped at Hospital",
"Car vs Pole",
"Car Chase With Foot Bail",
"Hit & Run",
"K9 Used",
"Vehicle Collision",
"Kum & Go Robbery",
"Casey's Robbery",
"QuikTrip Robbery",
"Call For Paddy Wagon",
"Red Team Alert",
"Spitter",
"Naked Person",
"123: Can You Hear Me Now?",
"Car vs Building",
"Transporting Cooperative",
"Transporting Uncooperative",
"Traffic Stop for Speeding",
"BOLO Issued",
"123: Having a Chitty Chat",
"Passed Out Behind the Wheel",
"Fighting With One",
"Fight in the Street",
"Fire Call: Burnt Food",
"Transformer on Fire",
"Call For Extra Cops on Court Ave",
"Wrong Way Driver",
"Chase Terminated",
"Stolen Vehicle",
"Urinating in Public",
"Happy Birthday Over the Radio",
"DPQ Loud Music",
"Fight in the Parking Garage",
"Vehicle on Fire",
"Drag Racers",
"Theft of Catalytic Converter",
"Elevator Rescue",
"Free Stuff On the Road",
"Fire at Homeless Camp",
"Open Mic",
"Farm Animal Loose",
"Gun Found",
"Person with Sword",
"Person with Ax or Hatchet",
"Vehicle Blacked Out",
"Speeds Over 100",
"Spike Strip",
"Garage or Shed Fire",
"Fight Inside a Business",
"Taser Deployed",
"Detoured By a Train",
"Arcing and Sparking Line",
"Felony Stop",
"Vehicle Stuck in High Water",
"AIR",
"Police Car in Accident",
"House Fire",
];
