const text = [
"Person With Machete or Sword",
"Git n Go Robbery",
"Intox Driver",
"Car Chase",
"Foot Chase",
"Suspect on a Bicycle",
"10-99 Wanted Person",
"Hazmat Response",
"Shooting Victim",
"'Shots Heard' = Fireworks",
"No Plates",
"Court Ave Fight",
"Drive-By Shooting",
"Stabbing Victim",
"Car vs Pole",
"Hit & Run",
"K9 Used",
"Vehicle Collision",
"Kum & Go Robbery",
"Casey's Robbery",
"QuikTrip Robbery",
"Call For Wagon",
"Red Team Alert",
"Naked Person",
"Can You Hear Me Now?",
"Car vs Building",
"Transporting Cooperative",
"Transporting Uncooperative",
"Traffic Stop for Speeding",
"BOLO Dispatched",
"123: Having a Chitty Chat",
"Passed Out Behind the Wheel",
"Fighting With One",
"Fight in the Street",
"Fire Call: Burnt Food",
"Blown Transformer",
"Wrong Way Driver",
"Chase Terminated",
"Stolen Vehicle",
"Urinating in Public",
"DPQ Loud Music",
"Vehicle on Fire",
"Drag Racers",
"Catalytic Converter Theft",
"Elevator Rescue",
"Free Stuff On the Road",
"Open Mic",
"Farm Animal Loose",
"Gun Found",
"Person with Ax or Hatchet",
"Vehicle Blacked Out",
"Speeds Over 100",
"Garage or Shed Fire",
"Fight Inside a Business",
"Taser Deployed",
"Detoured By a Train",
"Arcing/Sparking Line",
"Felony Stop",
"Vehicle Stuck in High Water",
"AIR",
"Police Car in Accident",
"House Fire",
"Interstate Accident",
"Water Rescue",
"Welfare Check",
"Medics for Intox",
"Computer Problem",
"'Stolen' Car Was Towed",
"Crow Tow",
"In Custody/ Arrest Made",
"Detained",
"Background Yelling on Radio",
"Suspicious Activity",
"Assault",
"Neighbor Dispute",
"Prowler",
"Barking Dog",
"Found Property",
"Car vs Deer",
"B & E in Progress",
"Trespass",
"Pepper Spray",
"PIT Successful",
"PIT Approved",
"Decontamination Needed",
"Driver Passed Out",
];
