const text = [
"Person With Machete or Sword",
"Git n Go Robbery",
"Intox Driver",
"Vehicle Chase",
"Foot Chase",
"Suspect on a Bicycle",
"10-99 Wanted Person",
"Hazmat Response",
"Shooting Victim",
"'Shots Heard' = Fireworks",
"No Plates",
"Court Ave Fight",
"Bar Fight",
"Drive-By Shooting",
"Stabbing Victim",
"Car vs Pole",
"Hit & Run",
"K9 at Work",
"Vehicle Collision",
"Casey's Robbery",
"QuikTrip Robbery",
"Call For Wagon",
"Red Team Alert",
"Naked Person",
"Car vs Building",
"Transporting Cooperative",
"Transporting Uncooperative",
"Traffic Stop for Speeding",
"BOLO Dispatched",
"Passed Out Behind the Wheel",
"Fighting With One",
"Fight in the Street",
"Fire Call: Burnt Food",
"Blown Transformer",
"Wrong Way Driver",
"Chase Terminated",
"Stolen Vehicle",
"Urinating in Public",
"DPQ Loud Music",
"Vehicle on Fire",
"Drag Racers",
"Elevator Rescue",
"Free Stuff On the Road",
"Open Mic",
"Farm Animal Loose",
"Gun Found",
"Person with Ax or Hatchet",
"Vehicle Blacked Out",
"Speeds Over 100",
"Garage or Shed Fire",
"Fight Inside a Business",
"Taser Deployed",
"Detoured By a Train",
"Arcing/Sparking Wire",
"Felony Stop",
"AIR",
"Police Car in Accident",
"House Fire",
"Interstate Accident",
"Water Rescue",
"Medics for Intox",
"Cruiser Computer Problem",
"'Stolen' Car Was Towed",
"In Custody/ Arrest Made",
"Detained",
"Background Yelling on Radio",
"Suspicious Activity",
"Assault",
"Neighbor Dispute",
"Prowler",
"Barking Dog",
"Found Property",
"B & E in Progress",
"Trespass",
"Pepper Spray",
"PIT Successful",
"PIT Approved",
"Decontamination Needed",
"Suspect Wearing Mask",
"Apartment Complex Fire",
"Drugs found",
"Vehicle Blacked Out",
"Vehicle in Wrong Lanes",
"ISP Aircraft Assist",
"Channel 4E",
"Iowa Geography Game",
"Language Barrier",
];

